config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  root 'home#index'
  get '/categories/:id', to: 'categories#show', as: 'category'
  get '/allproducts', to: 'products#index', as: 'product_all'
  get '/products/:id', to: 'products#show', as: 'product'

  post 'products/add_to_cart', to: 'products#add_to_cart', as: 'add_to_cart'

  get '/cart', to: 'cart#index', as: 'cart'
  put '/cart', to: 'cart#update', as: 'update_cart'
  #post '/cart/remove', to: 'cart#remove', as: 'remove_on_cart'
  delete 'cart/remove_from_cart', to: 'cart#remove_from_cart', as: 'remove_from_cart'

  get '/search', to: 'search#index'

  get '/account/:id', to: 'account#show', as: 'account'
  get '/account/:id/edit', to: 'account#edit', as: 'account_edit'
  patch '/account/:id/edit', to: 'account#update', as: 'account_update'
  get '/account/:id/orders', to: 'account#get_orders', as: 'account_orders'

  get '/about', to: 'about#index', as: 'about'
  get '/contact', to: 'contact#index', as: 'contact'

  get '/checkout/address', to:'checkout#address', as:'checkout_address'
  post '/checkout/address/update', to:'checkout#address_update', as: 'checkout_address_update'
  get 'checkout/stripe', to: 'checkout#stripe', as: 'checkout_stripe'
  post '/checkout', to: 'checkout#index', as: 'checkout'

  get '/success', to: 'checkout#success'
  get '/cancel', to: 'checkout#cancel'
  devise_for :accounts
end

app/models/about.rb
class About < ApplicationRecord
    validates :title, :body, presence: true
    validates :title, length: { minimum: 3, maximum: 50 }
    validates :body, length: { minimum: 5}
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :validatable
    belongs_to :primary_province, class_name: 'Province', optional: true
    belongs_to :secondary_province, class_name: 'Province', optional: true
    has_many :orders
    has_many_attached :images

    validates :email, presence: true
    #validates :primarypostalcode,  format: { with: /\A[A-Za-z]\d[A-Za-z]\s?\d[A-Za-z]\d\z/, message: "Invalid postal code format" }
    validates :primarypostalcode, postal_code: true
    validates :secondarypostalcode, postal_code: true
    #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :categoryname, presence: true
    validates :categoryname, length: { minimum: 3, maximum: 50 }
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :phonenumber, :email, :openinghours, presence: true
    validates :phonenumber, format: { with: /\A(\+?1\s?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/, message: "Invalid phone number format" }
    validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "Invalid email format" }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :account
  has_many :order_items

  #validates :orderdate, presence: true
  validates :shippingAddress, presence: true
  validates :paymentmethod, presence: true
  validates :status, presence: true
  validates :pst, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :gst, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :hst, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :product

    validates :quantity, :price, presence: true
    validates :quantity, numericality: { only_integer: true }
    validates :price, numericality: { greater_than: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_many_attached :images
  paginates_per 10
  validates :productname, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :amountinstock, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :primary_accounts, class_name: 'Account', foreign_key: 'primary_province_id'
  has_many :secondary_accounts, class_name: 'Account', foreign_key: 'secondary_province_id'

  validates :provincename, presence: true
  validates :taxtype, presence: true
  validates :pst, numericality: { greater_than_or_equal_to: 0 }
  validates :gst, numericality: { greater_than_or_equal_to: 0 }
  validates :hst, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @products = Product.find(@cart.map { |a| a['id'] })

    @estimated = 0.0
    @cart.each do |item|
      @estimated += (item['qty'] * (@products.select {|p| p.id == item['id']}).first.price)
    end

    # If the signed in user has no primary or secondary address on file
    if account_signed_in?
      user = Account.find(current_account.id)
      if user.primary_province_id.present?
        @taxprovince = user.primary_province_id
      elsif user.secondary_province_id.present?
        @taxprovince = user.secondary_province_id
      else
        @taxprovince = nil
      end
    else
      if session[:province_id].present?
        @taxprovince = session[:province_id]
      else
        @taxprovince = nil
      end
    end

    # IF province is avaliable calculate the tax and display
    if !@taxprovince.nil?
      p = Province.find(@taxprovince)
      @tax = ((@estimated * (p.pst + p.gst + p.hst))/100)
    end

    #puts @cart.inspect
    #puts @estimated.inspect
  end

  def update
    puts params
    qty = params[:quantity_param].to_i
    id = params[:id].to_i

    cart = session[:cart].select { |a| a['id'] != id }
    session[:cart] = cart

    # Check if the value is different from what is already in the cart, and update accordingly.
    existing_item = session[:cart].find { |a| a['id'] == id }
    if existing_item
      existing_item['qty'] = qty
    else
      new_item = { 'id' => id, 'qty' => qty }
      session[:cart] << new_item
    end

    # Remove the item from the cart if the quantity becomes zero
    session[:cart].delete_if { |a| a['id'] == id && a['qty'] == 0 }

    redirect_to cart_path
  end

  def remove_from_cart
    id = params[:id].to_i
    returnto = params[:where]
    puts returnto
    cartitem = session[:cart].delete_if { |a| a['id'] == id}

    if returnto == 'P'
      redirect_to product_path(id)
    elsif returnto == 'C'
      redirect_to cart_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.shuffle.take(6)

    # Product is new if created date and updated date is within the last 3 days
    @newproducts = Product.where('created_at >= ?', 3.days.ago.to_date).where("strftime('%Y-%m-%dT%H:%M:00', created_at) = strftime('%Y-%m-%dT%H:%M:00', updated_at)").take(3)


    # Product is updated if updated date is within the last 3 days
    @updatedproducts = Product.where('updated_at >= ?', 3.days.ago).where("strftime('%Y-%m-%dT%H:%M:00', created_at) != strftime('%Y-%m-%dT%H:%M:00', updated_at)").order(updated_at: :desc).limit(3)
                              #.shuffle.order('updated_at DESC')
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/cart/index.html.erb
<section class="mt-5">
<h1 class="is-size-2 mt-6 mb-6 has-text-centered"> Your Cart </h1>
<p class="mb-5">
    You have <span class="is-link"><%= @cart.count %></span> items in your cart.
</p>

<% @cart.each do |item| %>
<% product = @products.find { |p| p.id == item['id'] } %>
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <% if product.images.first.present? %>
        <%= image_tag(product.images.first.variant(resize_to_limit: [100,100])) %>
      <% else %>
        <p>No Image</p>
      <% end %>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= product.productname %></strong>
        <form action="<%= update_cart_path %>" method="post">
            <p>
                <%= number_field_tag 'quantity_param', item['qty'], min: 0, max: product['amountinstock'] , class: "button"%>

                <%= button_to 'update', update_cart_path, params: { id: item['id'] }, method: :put, class: "button" %>
            </p>
            <p>
                <%= button_to 'remove', remove_from_cart_path, params: { id: item['id'], where: 'C' }, method: :delete, class: "button is-warning" %>
            </p>
        </form>
      </p>
    </div>
  </div>
</article>
<% end %>


<p class="has-text-left mt-5">
    Total Before Tax: <%= number_to_currency(@estimated, precision: 2) %>
</p>
<% if @taxprovince.nil? %>
    <p>
        You must provide your address before final price can be determined. Select place order and enter your address.
    </p>
<% else %>
    <p>
        Tax: <%= number_to_currency(@tax, precision: 2) %>
    </p>
    <p>
        Estimated Total: <%= number_to_currency(@estimated + @tax, precision: 2) %>
    </p>
<% end %>

<div data-turbo='false' class="mt-5">
<%= form_with url: checkout_path do |f| %>
    <%= f.submit 'Place Order', class: "button is-link" %>
<% end %>
</div>

</section>

app/views/home/_footer.html.erb
<footer class="footer is-fixed-bottom">
  <div class="container">
    <div class="columns">
      <div class="column is-one-third">
        <h3 class="title is-5">Contact Us</h3>
        <p>
          Address: 123 Main Street, Winnipeg<br>
          Phone: (123) 456-7890<br>
          Email: info@bikazon.com
        </p>
      </div>
      <div class="column is-one-third">
        <h3 class="title is-5">Quick Links</h3>
        <ul>
          <li><%= link_to 'Home',root_path %></li>
          <li><%= link_to 'Products',product_all_path %></li>
          <li><%= link_to 'About Us', about_path %></li>
          <li><%= link_to 'Contact Us', contact_path %></li>
        </ul>
      </div>
      <div class="column is-one-third">
        <h3 class="title is-5">Follow Us</h3>
        <div class="field is-grouped">
          <p class="control">
            <a href="#" class="button is-link is-small">
              <span class="icon">
                <i class="fab fa-facebook-f"></i>
              </span>
            </a>
          </p>
          <p class="control">
            <a href="#" class="button is-link is-small">
              <span class="icon">
                <i class="fab fa-twitter"></i>
              </span>
            </a>
          </p>
          <p class="control">
            <a href="#" class="button is-link is-small">
              <span class="icon">
                <i class="fab fa-instagram"></i>
              </span>
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/home/_menu.html.erb
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
    <div class="container">
    <div class="navbar-brand">
        <a class="navbar-item is-uppercase has-text-weight-bold" href="/">
        Bikazon
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="menuitem">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="menuitem" class="navbar-menu">
        <div class="navbar-start">
            <div class="navbar-item">
                <%= link_to 'Home', root_path, class: "navbar-item"  %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Account</a>
                    <div class="navbar-dropdown">
                        <%= link_to 'View Cart', cart_path, class: "navbar-item"%>
                        <% if account_signed_in? %>
                            <%= link_to 'View Account', account_path(current_account.id), class: "navbar-item" %>
                            <%= link_to 'View Orders', account_orders_path(current_account.id), class: "navbar-item" %>
                        <% end %>
                    </div>
                </div>
                <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">Categories</a>
                        <div class="navbar-dropdown">
                            <% @categories.each do |category| %>
                                <%= link_to category.categoryname, category_path(category), class: "navbar-item" %>
                            <% end %>
                        </div>
                </div>

            </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item is-flex">
                <%= form_with url: "/search", method: :get do |form| %>
                    <div class="field is-grouped">
                        <div class="control">
                            <%= form.label :query, "Find Products:" %>
                        </div>
                        <div class="control">
                            <%= form.text_field :query, class: "input is-link is-small"%>
                        </div>
                        <div class="control is-align-items-stretch">
                            <%= form.select :category, options_for_select(["All"] + @search_categories) %>
                        </div>
                        <div class="control">
                            <%= form.submit "Search",class: "button is-dark is-small"%>
                        </div>
                    </div>
                <% end %>
            </div>

            <div class="navbar-item">
                <% if account_signed_in? %>
                    <%= button_to "Logout", destroy_account_session_path, method: :delete, class: "button is-dark is-small" %>
                <% else %>
                    <%= link_to "Login", new_account_session_path, class: "button" %>
                <% end %>
            </div>
        </div>
    </div>
    </div>
</nav>

app/views/home/index.html.erb
 <section class="hero is-link">
    <div class="hero-body">

<p class="title">Welcome to Bikazon</p>
<p>Your premier destination for motorcycles and accessories in Winnipeg! With over 30 years of experience,
we take pride in delivering world-renowned, high-quality motorcycles to our passionate community of riders. Our dedicated team of 50 skilled staff members,
including salespeople, mechanics, administrative staff, and customer service representatives,
is committed to ensuring your satisfaction.</p>
<br>
<p>
  Since 1993, Bikazon has been a trusted name in the motorcycle industry,
  known for our expertise and exceptional customer service. We offer a diverse range of motorcycles from leading manufacturers,
  including sport bikes, cruisers, touring bikes, and off-road motorcycles. Additionally, we provide an extensive selection of motorcycle parts,
  accessories, safety gear, and apparel, carefully curated to meet the needs and preferences of motorcycle enthusiasts like you.
</p>
<br>
<p>
  Our physical showroom, strategically located in Winnipeg,
  invites you to explore our wide range of motorcycles on display. Our knowledgeable staff is always ready to assist you,
  offering personalized customer service and expert advice to help you find the perfect motorcycle for your needs.
  We understand that each rider is unique, and our goal is to ensure your buying experience is exceptional.
</p>
<br>
<p>
  In addition to motorcycles, Bikazon also offers a wide array of motorcycle parts, accessories, safety gear,
  and apparel. We carefully choose our products to ensure they meet the highest standards of quality,
  allowing riders to fully enjoy their passion while prioritizing safety and style.
</p>
<br>
<p>
  <%= link_to 'Checkout Our Products', product_all_path , class: "button is-white" %>
</p>
</div>
</section>


<h2 class="subtitle mt-6 mb-6 has-text-centered"> Our Newest Products </h2>

<div class="columns is-centered">
    <% @newproducts.each do |product| %>
        <div class="column is-one-third">
            <div class="card card-fixed-size is-flex is-flex-direction-column is-align-items-center has-text-centered">
                <div class="card-image">
                  <figure class="image is-4by3">
                      <% if product.images.first.present? %>
                            <figure class="image is-128x128">
                          <%= image_tag(product.images.first.variant(resize_to_limit: [400,400])) %>
                            </figure>
                       <% else %>
                          <p>No Image</p>
                      <% end %>
                  </figure>
                </div>
                <div class="card-content">
                  <%= product.productname%><br>
                  <%= number_to_currency(product.price) %><br>
                  <%= link_to 'Check It Out!', product_path(product), class: 'button is-link is-light' %>
                </div>
            </div>
        </div>
    <% end %>
</div>

<h2 class="subtitle mt-6 mb-6 has-text-centered"> Recently Updated Products </h2>

<div class="columns is-centered">
  <% @updatedproducts.each do |product| %>
    <div class="column is-one-third">
            <div class="card card-fixed-size is-flex is-flex-direction-column is-align-items-center has-text-centered">
                <div class="card-image">
                  <figure class="image is-4by3">
                      <% if product.images.first.present? %>
                            <figure class="image is-128x128">
                          <%= image_tag(product.images.first.variant(resize_to_limit: [400,400])) %>
                            </figure>
                       <% else %>
                          <p>No Image</p>
                      <% end %>
                  </figure>
                </div>
                <div class="card-content">
                  <%= product.productname%><br>
                  <%= number_to_currency(product.price) %><br>
                  <%= link_to 'Check It Out!', product_path(product), class: 'button is-link is-light' %>
                </div>
            </div>
        </div>
  <% end %>
</div>