config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  root 'home#index'
  get '/categories/:id', to: 'categories#show', as: 'category'
  get '/allproducts', to: 'products#index', as: 'product_all'
  get '/products/:id', to: 'products#show', as: 'product'

  post 'products/add_to_cart', to: 'products#add_to_cart', as: 'add_to_cart'

  get '/cart', to: 'cart#index', as: 'cart'
  put '/cart', to: 'cart#update', as: 'update_cart'
  #post '/cart/remove', to: 'cart#remove', as: 'remove_on_cart'
  delete 'cart/remove_from_cart', to: 'cart#remove_from_cart', as: 'remove_from_cart'

  get '/search', to: 'search#index'

  get '/account/:id', to: 'account#show', as: 'account'
  get '/account/:id/edit', to: 'account#edit', as: 'account_edit'
  patch '/account/:id/edit', to: 'account#update', as: 'account_update'
  get '/account/:id/orders', to: 'account#get_orders', as: 'account_orders'

  get '/about', to: 'about#index', as: 'about'
  get '/contact', to: 'contact#index', as: 'contact'

  get '/checkout/address', to:'checkout#address', as:'checkout_address'
  post '/checkout/address/update', to:'checkout#address_update', as: 'checkout_address_update'
  get 'checkout/stripe', to: 'checkout#stripe', as: 'checkout_stripe'
  post '/checkout', to: 'checkout#index', as: 'checkout'

  get '/success', to: 'checkout#success'
  get '/cancel', to: 'checkout#cancel'
  devise_for :accounts
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    # If they do, proceed to Stripe Payment
    #
    #
    #
    #

    def index
        # If cart is empty just return
        if @cart.length == 0
            redirect_to cart_path
            return
        end
        # Check If the user is logged in.
        if account_signed_in?
            # If they are logged in, Check If they have an address on file
            @account = Account.find(current_account.id)
            puts @account.inspect
            if @account.primaryaddressstreet.present?
                address = @account.primaryaddressstreet
                postalcode = @account.primarypostalcode
                province = @account.primary_province_id#Province.find(@account.primary_province_id).provincename
            elsif @account.secondaryaddressstreet.present?
                address = @account.secondaryaddressstreet
                postalcode = @account.secondarypostalcode
                province = @account.secondary_province_id#Province.find(@account.secondary_province_id).provincename
            else
                address = nil
            end

            # If they Don't have an address, let them enter the Address, then proceed
            if address == nil
                #redirect_to checkout_address_path
                render :address
                return
            # else
            #     # If they have an address and are sign in, send to stripe action
            #     redirect_to checkout_stripe_path
            end
        else
            # If the user is not logged in, Ask for the address and proceed to Check out
            if session[:addressstreet].blank?
                #redirect_to checkout_address_path
                render :address
                return
                # else
                #     # No logged in user but has entered address send to stripe action
                #     redirect_to checkout_stripe_path
            end
        end

        if !account_signed_in?
            address = session[:addressstreet]
            postalcode = session[:postalcode]
            province = session[:province_id]#Province.find(session[:province_id]).provincename
        end

        # Setup details to charge customer for
        currency = 'CAD'
        data = @cart.map { |cartitem|
            product = Product.find(cartitem['id'])
            purchaseitem = {
                currency: currency,
                unit_amount: (product.price * 100).to_i,
                name: product.productname,
                description: product.description,
                quantity: cartitem['qty'],
                id: cartitem['id']
            }
        }

        total_tax = data.reduce(0) do |sum, item|
            sum + item[:unit_amount] * item[:quantity]
        end
        #puts total_sum
        p = Province.find(province)
        tax = {
            currency: currency,
            unit_amount: ((total_tax * (p.pst + p.gst + p.hst))/100).to_i,
            name: p.provincename + ' Tax',
            description: p.taxtype,
            quantity: 1,
            id: 0
        }
        data << tax

        puts data
        console
        #debugger
        #generate Stripe session and send customer
        session = Stripe::Checkout::Session.create({
            line_items: [
                data.map do |d|
                    {
                    price_data: {
                        currency: d[:currency],
                        unit_amount: d[:unit_amount],
                        product_data: {
                            name: d[:name],
                            description: d[:description],
                            #images: 'image_url,
                            metadata: {
                                product_id: d[:id]
                                }
                            }
                        },
                    quantity: d[:quantity]
                    }

                end
        ],
            mode: 'payment',
            success_url: "#{ENV['NGROK']}/success?session_id={CHECKOUT_SESSION_ID}",
            cancel_url: "#{ENV['NGROK']}/cancel.html",
            metadata: {
                address: address,
                postalcode: postalcode,
                province: Province.find(province).provincename,
                cart: @cart.to_json,
                account_id: account_signed_in? ? current_account.id.to_s : 'N/A',
            },
            customer_email: account_signed_in? ? @account.email : nil
          })
         puts session.inspect
         #debugger
         redirect_to session.url, allow_other_host: true, status: 303
    end

    def address_update
        puts params
        if account_signed_in?
            account = Account.find(current_account.id)
            account.primaryaddressstreet = params["addressstreet"]
            account.primarypostalcode = params["postalcode"]
            account.primary_province_id = params["primary_province_id"]
            puts account.inspect
            account.save
        else
            session[:addressstreet] ||= params["addressstreet"]
            session[:postalcode] ||= params["postalcode"]
            session[:province_id] ||= params["primary_province_id"]
        end
        redirect_to cart_path
    end

    def success
        if !params[:session_id].nil?
            session = Stripe::Checkout::Session.retrieve(params[:session_id])
            payment_intent = Stripe::PaymentIntent.retrieve(session["payment_intent"])
            charge = Stripe::Charge.retrieve(payment_intent['latest_charge'])
            puts session.inspect

            @purchased = JSON.parse(session["metadata"]["cart"])
            @total = session["amount_total"].to_d
            @buyer = {
                address: session[:metadata][:address],
                postalcode: session[:metadata][:postalcode],
                province: session[:metadata][:province],
                invoice_url: charge['receipt_url'],
                email: session[:metadata][:account_id] == "N/A" ? session[:customer_details][:email] : Account.find(session[:metadata][:account_id].to_i).email
            }
            puts @buyer.inspect
            province = Province.where(provincename: session[:metadata][:province]).take
            #Create an Order Record
            order = Order.new(
                paymentmethod: session[:payment_method_types][0],
                shippingAddress: session[:metadata][:address] + ' ' + session[:metadata][:postalcode] + ' ' + session[:metadata][:province],
                status: 'paid',
                pst: province.pst,
                gst: province.gst,
                hst: province.hst,
                stripe_session: session[:id],
                account_id: session[:metadata][:account_id] == 'N/A' ? nil : Account.find(session[:metadata][:account_id].to_i).id
            )
            puts order.inspect
            @oorder = order
            order.save

            # Update the products table with amount in stock
            @oorderitem = []
            @purchased.each do |item|
                prod = Product.find(item['id'])
                prod.amountinstock = prod.amountinstock - 2

                # Create OrderItems For each item
                orderitem = OrderItem.new(
                    price: prod.price,
                    quantity: item['qty'],#.to_i
                    order_id: order.id,
                    product_id: prod.id
                    )
                puts orderitem.inspect
                @oorderitem << orderitem
                orderitem.save
                prod.save
            end

            if session[:cart].present?
                session.delete(:cart)
            end
        end
    end

    def cancel

        # Expire the stripe checkout session
    end


end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/checkout/address.html.erb
<section class="mt-5">
<h1 class="is-size-2 mt-6 mb-6 has-text-centered"> Enter Your Address Details </h1>


<div class="container">
  <div class="columns">
    <div class="column is-one-third">
<%= form_with url: checkout_address_update_path do |form| %>
  <div class="field">
    <%= form.label :addressstreet , class: "label" %>
    <%= form.text_field :addressstreet, required: true, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :postalcode, class: "label" %>
    <%= form.text_field :postalcode, required: true, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :primary_province_id, class: "label" %>
    <div class="select">
    <%= form.collection_select :primary_province_id, Province.all, :id, :provincename, { prompt: true }, required: true %>
    </div>
  </div>

   <div class="field is-grouped">
    <div class="control">
    <%= form.submit "Submit Address", class: 'button is-link' %>
  </div>
    <div class="control">
    <%= link_to 'Back', cart_path, class: 'button is-link is-light' %>
  </div>
  </div>

<% end %>


<div class="column"></div>
  <div class="column"></div>
  </div>
</div>
</section>

app/views/checkout/cancel.html.erb
 <section class="mt-5">
    <h1 class="is-size-2 mt-6 mb-6 has-text-centered"> Opps! </h1>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
    <%= link_to 'Continue browsing', product_all_path , class: "button is-link mt-5" %>
  </section>

app/views/checkout/success.html.erb
<section class="mt-5">
<h1 class="is-size-2 mt-6 mb-6 has-text-centered"> Thanks for your order! </h1>
<h2 class="subtitle">  We here at Bikazon really appreciate your support! </h2>
<h3>Here's a summary of your order:</h3>
        <table class="table mt-5 is-fullwidth">
            <tr>
                <th colspan="4"><strong>Address Information</strong></th>
            </tr>
            <tr>
                <td class="alignright"><strong>Address:</strong></td>
                <td><%= @buyer[:address] %></td>
                <td class="alignright"><strong>Postal Code:</strong></td>
                <td><%= @buyer[:postalcode] %></td>
            </tr>
            <tr>
                <td class="alignright"><strong>Province:</strong></td>
                <td><%= @buyer[:province] %></td>
                <td colspan="2" class="alignright"><strong>Email:</strong></td>
                <td colspan="2"><%= @buyer[:email] %></td>
            </tr>
            <tr>
                <td class="alignright"><strong>View Your Invoice</strong></td>
                <td><a href="<%= @buyer[:invoice_url] %>" target="_blank" rel="noopener noreferrer" >Invoice</a></td>
            </tr>
        </table>
        <table class="table">
            <tr>
                <td colspan="3"><strong>Order Details</strong></td>
            </tr>
            <tr>
                <td><strong>Quantity</strong></td>
                <td><strong>Description</strong></td>
                <td><strong>Cost</strong></td>
            </tr>
            <% @oorderitem.each do |orderitem| %>
                <tr>
                    <td><%= orderitem.quantity %></td>
                    <td><%= Product.find(orderitem.product_id).productname %></td>
                    <td><%= orderitem.price %></td>
                </tr>
            <% end %>
            <tr>
                <td></td>
                <td><strong>Totals:</strong></td>
                <td><%= @total %></td>
            </tr>
        </table>
        </section>