config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  root 'home#index'
  get '/categories/:id', to: 'categories#show', as: 'category'
  get '/allproducts', to: 'products#index', as: 'product_all'
  get '/products/:id', to: 'products#show', as: 'product'

  post 'products/add_to_cart', to: 'products#add_to_cart', as: 'add_to_cart'

  get '/cart', to: 'cart#index', as: 'cart'
  put '/cart', to: 'cart#update', as: 'update_cart'
  #post '/cart/remove', to: 'cart#remove', as: 'remove_on_cart'
  delete 'cart/remove_from_cart', to: 'cart#remove_from_cart', as: 'remove_from_cart'

  get '/search', to: 'search#index'

  get '/account/:id', to: 'account#show', as: 'account'
  get '/account/:id/edit', to: 'account#edit', as: 'account_edit'
  patch '/account/:id/edit', to: 'account#update', as: 'account_update'
  get '/account/:id/orders', to: 'account#get_orders', as: 'account_orders'

  get '/about', to: 'about#index', as: 'about'
  get '/contact', to: 'contact#index', as: 'contact'

  get '/checkout/address', to:'checkout#address', as:'checkout_address'
  post '/checkout/address/update', to:'checkout#address_update', as: 'checkout_address_update'
  get 'checkout/stripe', to: 'checkout#stripe', as: 'checkout_stripe'
  post '/checkout', to: 'checkout#index', as: 'checkout'

  get '/success', to: 'checkout#success'
  get '/cancel', to: 'checkout#cancel'
  devise_for :accounts
end

app/models/about.rb
class About < ApplicationRecord
    validates :title, :body, presence: true
    validates :title, length: { minimum: 3, maximum: 50 }
    validates :body, length: { minimum: 5}
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :validatable
    belongs_to :primary_province, class_name: 'Province', optional: true
    belongs_to :secondary_province, class_name: 'Province', optional: true
    has_many :orders
    has_many_attached :images

    validates :email, presence: true
    #validates :primarypostalcode,  format: { with: /\A[A-Za-z]\d[A-Za-z]\s?\d[A-Za-z]\d\z/, message: "Invalid postal code format" }
    validates :primarypostalcode, postal_code: true
    validates :secondarypostalcode, postal_code: true
    #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :categoryname, presence: true
    validates :categoryname, length: { minimum: 3, maximum: 50 }
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :phonenumber, :email, :openinghours, presence: true
    validates :phonenumber, format: { with: /\A(\+?1\s?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/, message: "Invalid phone number format" }
    validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "Invalid email format" }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :account
  has_many :order_items

  #validates :orderdate, presence: true
  validates :shippingAddress, presence: true
  validates :paymentmethod, presence: true
  validates :status, presence: true
  validates :pst, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :gst, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :hst, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :product

    validates :quantity, :price, presence: true
    validates :quantity, numericality: { only_integer: true }
    validates :price, numericality: { greater_than: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_many_attached :images
  paginates_per 10
  validates :productname, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :amountinstock, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :primary_accounts, class_name: 'Account', foreign_key: 'primary_province_id'
  has_many :secondary_accounts, class_name: 'Account', foreign_key: 'secondary_province_id'

  validates :provincename, presence: true
  validates :taxtype, presence: true
  validates :pst, numericality: { greater_than_or_equal_to: 0 }
  validates :gst, numericality: { greater_than_or_equal_to: 0 }
  validates :hst, numericality: { greater_than_or_equal_to: 0 }
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikazon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
        <%= render "home/menu"%>
  <section class="section">
      <div class="container">

        <% if notice %>
          <div class="notification is-primary">
            <%= notice %>
          </div>
        <% end %>

        <% if alert %>
          <div class="notification is-danger">
            <%= alert %>
          </div>
        <% end %>

        <%= yield %>
      </div>
  </section>
    <%= render "home/footer" %>
  <script defer src="https://use.fontawesome.com/releases/v5.15.3/js/all.js"></script>
  </body>
</html>

app/views/shared/_products.html.erb
<div class="container">
  <div class="columns">
    <div class="column"></div>
    <div class="column"></div>
    <div class="column is-one-fifth">
      <!-- Your main content goes here -->
      <%= paginate products, previous_label: "&laquo; Previous", next_label: "Next &raquo;", class: "pagination is-centered" %>
    </div>
  </div>
</div>

<% products.each do |product| %>
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <% if product.images.first.present? %>
        <%= image_tag(product.images.first.variant(resize_to_limit: [100,100])) %>
      <% else %>
        <p>No Image</p>
      <% end %>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= product.productname %></strong>
        <br>
        <%= product.description %>
      </p>
      <small><%= link_to 'Check It Out!', product_path(product), class: 'button is-link is-light' %></small>
    </div>
  </div>
</article>
<% end %>