config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  root 'home#index'
  get '/categories/:id', to: 'categories#show', as: 'category'
  get '/allproducts', to: 'products#index', as: 'product_all'
  get '/products/:id', to: 'products#show', as: 'product'

  post 'products/add_to_cart', to: 'products#add_to_cart', as: 'add_to_cart'

  get '/cart', to: 'cart#index', as: 'cart'
  put '/cart', to: 'cart#update', as: 'update_cart'
  #post '/cart/remove', to: 'cart#remove', as: 'remove_on_cart'
  delete 'cart/remove_from_cart', to: 'cart#remove_from_cart', as: 'remove_from_cart'

  get '/search', to: 'search#index'

  get '/account/:id', to: 'account#show', as: 'account'
  get '/account/:id/edit', to: 'account#edit', as: 'account_edit'
  patch '/account/:id/edit', to: 'account#update', as: 'account_update'
  get '/account/:id/orders', to: 'account#get_orders', as: 'account_orders'

  get '/about', to: 'about#index', as: 'about'
  get '/contact', to: 'contact#index', as: 'contact'

  get '/checkout/address', to:'checkout#address', as:'checkout_address'
  post '/checkout/address/update', to:'checkout#address_update', as: 'checkout_address_update'
  get 'checkout/stripe', to: 'checkout#stripe', as: 'checkout_stripe'
  post '/checkout', to: 'checkout#index', as: 'checkout'

  get '/success', to: 'checkout#success'
  get '/cancel', to: 'checkout#cancel'
  devise_for :accounts
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_many_attached :images
  paginates_per 10
  validates :productname, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :amountinstock, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart

      cartitem = { 'id' => params[:id].to_i, 'qty' => params[:quantity_param].to_i}
      #session[:cart] << id unless session[:cart].include? (id)

      #puts session[:cart].includes(:id).where('')
      session[:cart] << cartitem unless session[:cart].any? do |item| item['id'] == cartitem['id'] end
      #puts session[:cart]

      redirect_to product_path(params[:id].to_i)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<section class=" mt-5">

<%= render "shared/products" , products: @products %>

</section>

app/views/products/show.html.erb
<section class="mt-5">

<div class="card">
  <div class="card-image is-flex is-justify-content-space-evenly">
      <% if @product.images.first.present? %>
        <% @product.images.each do |image| %>
    <figure class="image is-128x128">
            <%= image_tag(image.variant(resize_to_limit: [400,400])) %>
    </figure>
          <% end %>
      <% else %>
        <p>No Image</p>
      <% end %>
  </div>
  <div class="card-content">
    <div class="media">

      <div class="media-content">
        <p class="title is-4"><%= @product.productname %></p>
        <p class="subtitle is-6"><%= number_to_currency @product.price %></p>
      </div>
    </div>

    <div class="content">
      <%= @product.description %>
      <br>
      <p></p>
      <% if @cart.any? do |cartitem| cartitem['id'] == @product.id end %>
            <%= button_to 'remove from cart', remove_from_cart_path, params: { id: @product.id, where: 'P' }, method: :delete, class: "button is-warning" %>
      <% else %>
            <form action="<%= add_to_cart_path %>" method="post">
                <%= number_field_tag 'quantity_param', 1, min: 1, max: @product.amountinstock, class: "select is-link" %>&nbsp;<%= button_to 'Add To Cart', add_to_cart_path, params: { id: @product.id }, method: :post, class: "button" %>
            </form>
      <% end %>
    </div>
  </div>
</div>

</section>